# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField(null=True)),
                ('ColumnName', models.CharField(max_length=30, null=True)),
                ('ColumnValue', models.CharField(max_length=30, null=True)),
                ('ErrorMessage', models.CharField(max_length=30, null=True)),
                ('UpdatedOn', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawBillingRecord',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(max_length=30, null=True)),
                ('UHID', models.CharField(max_length=30, null=True)),
                ('AdmissionNumber', models.CharField(max_length=30, null=True)),
                ('RegistrationDate', models.CharField(max_length=30, null=True)),
                ('RegistrationNumber', models.CharField(max_length=30, null=True)),
                ('BillingDate', models.CharField(max_length=30, null=True)),
                ('BillingNumber', models.CharField(max_length=30, null=True)),
                ('TimeOfBilling', models.CharField(max_length=30, null=True)),
                ('PatientZIP', models.CharField(max_length=30, null=True)),
                ('PatientDateOfBirth', models.CharField(max_length=30, null=True)),
                ('PatientGender', models.CharField(max_length=30, null=True)),
                ('ServiceCode', models.CharField(max_length=30, null=True)),
                ('ServiceName', models.CharField(max_length=30, null=True)),
                ('NumberOfUnitsOfService', models.CharField(max_length=30, null=True)),
                ('ServiceAmount', models.CharField(max_length=30, null=True)),
                ('DoctorName', models.CharField(max_length=30, null=True)),
                ('FinalBillAmount', models.CharField(max_length=30, null=True)),
                ('FinalDiscountAmount', models.CharField(max_length=30, null=True)),
                ('PaymentMode', models.CharField(max_length=30, null=True)),
                ('PaymentAmount', models.CharField(max_length=30, null=True)),
                ('PaymentDate', models.CharField(max_length=30, null=True)),
                ('FinalBillingID', models.CharField(max_length=30, null=True)),
                ('FinalEncounterID', models.CharField(max_length=30, null=True)),
                ('InsuranceCoverage', models.CharField(max_length=30, null=True)),
                ('EmployerBasedInsurance', models.CharField(max_length=30, null=True)),
                ('InsuranceCompanyName', models.CharField(max_length=30, null=True)),
                ('PatientEducation', models.CharField(max_length=30, null=True)),
                ('EmploymentType', models.CharField(max_length=30, null=True)),
                ('PatientEmployer', models.CharField(max_length=30, null=True)),
                ('PatientAnnualIncomeRange', models.CharField(max_length=30, null=True)),
                ('FrequencyOfGleneaglesVisit', models.CharField(max_length=30, null=True)),
                ('LifestylePattern', models.CharField(max_length=30, null=True)),
                ('TreatmentPlan', models.CharField(max_length=30, null=True)),
                ('Rx', models.CharField(max_length=30, null=True)),
                ('TestsPrescribed', models.CharField(max_length=30, null=True)),
                ('NextVisitDate', models.CharField(max_length=30, null=True)),
                ('Referrals', models.CharField(max_length=30, null=True)),
                ('UpdatedBy', models.CharField(max_length=30, null=True)),
                ('UpdatedOn', models.DateTimeField(verbose_name=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedBillingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('RecordID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('UHID', models.IntegerField()),
                ('AdmissionNumber', models.IntegerField()),
                ('RegistrationDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920251))),
                ('RegistrationNumber', models.IntegerField()),
                ('BillingNumber', models.IntegerField()),
                ('TimeOfBilling', models.TimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920307))),
                ('PatientZIP', models.IntegerField()),
                ('PatientDateOfBirth', models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920334))),
                ('PatientGender', models.CharField(max_length=30)),
                ('ServiceCode', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=30)),
                ('NumberOfUnitsOfService', models.IntegerField()),
                ('ServiceAmount', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=30)),
                ('FinalBillAmount', models.IntegerField()),
                ('FinalDiscountAmount', models.IntegerField()),
                ('PaymentMode', models.CharField(max_length=30)),
                ('PaymentAmount', models.IntegerField(default=1)),
                ('PaymentDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920455))),
                ('FinalBillingID', models.IntegerField()),
                ('FinalEncounterID', models.IntegerField()),
                ('InsuranceCoverage', models.CharField(max_length=30)),
                ('EmployerBasedInsurance', models.CharField(max_length=30)),
                ('InsuranceCompanyName', models.CharField(max_length=30)),
                ('PatientEducation', models.CharField(max_length=30)),
                ('EmploymentType', models.CharField(max_length=30)),
                ('PatientEmployer', models.CharField(max_length=30)),
                ('PatientAnnualIncomeRange', models.IntegerField()),
                ('FrequencyOfGleneaglesVisit', models.CharField(max_length=30)),
                ('LifestylePattern', models.CharField(max_length=30)),
                ('TreatmentPlan', models.CharField(max_length=30)),
                ('Rx', models.CharField(max_length=30)),
                ('TestsPrescribed', models.CharField(max_length=30)),
                ('NextVisitDate', models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920612))),
                ('Referrals', models.CharField(max_length=30)),
                ('UpdatedBy', models.CharField(max_length=30)),
                ('UpdatedOn', models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 29, 17, 30, 14, 920646))),
            ],
        ),
    ]
